const WORDS = window.PETS3_WORDS || [];
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const STORE = 'pets3-review-v1';
const state = Object.assign({mastered:[],learning:[],wrong:[],reviewIndex:0,quizCorrect:0,quizTotal:0,lastStudy:'',streak:0,tipsCompleted:[],customTips:[]}, JSON.parse(localStorage.getItem(STORE)||'{}'));
let session=[], current=0, quiz={mode:'choice',items:[],index:0,score:0,locked:false};
const save=()=>localStorage.setItem(STORE,JSON.stringify(state));
const sample=(arr,n)=>[...arr].sort(()=>Math.random()-.5).slice(0,n);
const toast=t=>{const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};

function initDay(){const today=new Date().toISOString().slice(0,10);if(state.lastStudy!==today){const yesterday=new Date(Date.now()-864e5).toISOString().slice(0,10);state.streak=state.lastStudy===yesterday?(state.streak||0)+1:1;state.lastStudy=today;save()}$('#today').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());}
function navigate(view){$$('.view,.nav').forEach(x=>x.classList.remove('active'));$(`#${view}View`).classList.add('active');$(`.nav[data-view="${view}"]`)?.classList.add('active');const titles={home:'学习首页',review:'单词复习',quiz:'单词测试',practice:'历年真题',listening:'听力训练',tips:'学习技巧',book:'错词本'};$('#pageTitle').textContent=titles[view];$('.sidebar').classList.remove('open');if(view==='review')startReview();if(view==='quiz'&&!quiz.items.length)startQuiz(quiz.mode);if(view==='book')renderBook();updateStats();}
$$('.nav').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>{if(b.dataset.mode)quiz.mode=b.dataset.mode;navigate(b.dataset.go)});$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');

function updateStats(){const mastered=new Set(state.mastered).size,learning=new Set(state.learning).size;$('#masteredStat').textContent=mastered;$('#dueStat').textContent=Math.min(30,Math.max(0,WORDS.length-mastered));$('#accuracyStat').textContent=state.quizTotal?Math.round(state.quizCorrect/state.quizTotal*100)+'%':'—';$('#progressText').textContent=`${mastered} / ${WORDS.length}`;$('#progressBar').style.width=`${mastered/WORDS.length*100}%`;$('#streakDays').textContent=`${state.streak||1} 天`;}

function startReview(){const wrongSet=new Set(state.wrong), masteredSet=new Set(state.mastered);const priority=WORDS.filter(w=>wrongSet.has(w.id));const fresh=WORDS.filter(w=>!masteredSet.has(w.id)&&!wrongSet.has(w.id));session=[...sample(priority,10),...sample(fresh,30)].slice(0,30);if(session.length<30)session=[...session,...sample(WORDS.filter(w=>!session.includes(w)),30-session.length)];current=0;showCard();}
function showCard(){const w=session[current]||WORDS[0];$('#flashcard').classList.remove('flipped');$('#reviewCount').textContent=current+1;$('#wordNo').textContent=`WORD ${String(w.id).padStart(3,'0')}`;$('#cardWord').textContent=w.word;$('#cardPhonetic').textContent=w.phonetic;$('#cardMeaning').textContent=w.meaning;}
$('#flashcard').onclick=()=>$('#flashcard').classList.toggle('flipped');$('#soundBtn').onclick=e=>{e.stopPropagation();speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(session[current]?.word||''));};
$$('[data-rate]').forEach(b=>b.onclick=()=>{const w=session[current],rate=b.dataset.rate;state.learning=state.learning.filter(id=>id!==w.id);state.mastered=state.mastered.filter(id=>id!==w.id);if(rate==='easy'){state.mastered.push(w.id);state.wrong=state.wrong.filter(id=>id!==w.id)}else{state.learning.push(w.id);if(rate==='again'&&!state.wrong.includes(w.id))state.wrong.push(w.id)}save();current++;if(current>=session.length){toast('今日复习完成！');navigate('home')}else showCard();});

function startQuiz(mode='choice'){quiz={mode,items:sample(WORDS,10),index:0,score:0,locked:false};$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.quizmode===mode));renderQuiz();}
$$('.tab').forEach(b=>b.onclick=()=>startQuiz(b.dataset.quizmode));
function renderQuiz(){if(quiz.index>=quiz.items.length){$('#quizBody').innerHTML=`<div class="result"><span>本组完成</span><strong>${quiz.score} / 10</strong><p>${quiz.score>=8?'很棒，保持这个节奏！':'错题已收入错词本，记得及时复习。'}</p><button class="primary" id="restartQuiz">再来一组</button></div>`;$('#restartQuiz').onclick=()=>startQuiz(quiz.mode);return}const w=quiz.items[quiz.index];$('#quizProgress').textContent=`第 ${quiz.index+1} / 10 题`;$('#quizScore').textContent=`得分 ${quiz.score}`;$('#quizBar').style.width=`${quiz.index*10}%`;quiz.locked=false;if(quiz.mode==='choice'){const options=sample(WORDS.filter(x=>x.id!==w.id),3).map(x=>x.meaning);options.push(w.meaning);const shuffled=sample(options,4);$('#quizBody').innerHTML=`<div class="quiz-question"><p>请选择正确的中文释义</p><h3>${w.word}</h3><span>${w.phonetic}</span></div><div class="options">${shuffled.map((o,i)=>`<button class="option" data-answer="${encodeURIComponent(o)}"><b>${String.fromCharCode(65+i)}.</b> ${o}</button>`).join('')}</div>`;$$('.option').forEach(b=>b.onclick=()=>answerChoice(b,w));}else{$('#quizBody').innerHTML=`<div class="quiz-question"><p>请根据释义拼写单词</p><h3>${w.meaning}</h3><span>${w.phonetic.replace(/[A-Za-z]/g,'•')}</span></div><div class="spell-input"><input id="spellAnswer" autocomplete="off" placeholder="输入英文单词"><button class="primary" id="submitSpell">提交</button></div>`;$('#submitSpell').onclick=()=>answerSpell(w);$('#spellAnswer').onkeydown=e=>{if(e.key==='Enter')answerSpell(w)};$('#spellAnswer').focus();}}
function recordAnswer(ok,w){state.quizTotal++;if(ok){quiz.score++;state.quizCorrect++;}else if(!state.wrong.includes(w.id))state.wrong.push(w.id);save();}
function answerChoice(btn,w){if(quiz.locked)return;quiz.locked=true;const val=decodeURIComponent(btn.dataset.answer),ok=val===w.meaning;recordAnswer(ok,w);$$('.option').forEach(b=>{const v=decodeURIComponent(b.dataset.answer);if(v===w.meaning)b.classList.add('correct');else if(b===btn)b.classList.add('wrong');b.disabled=true});nextButton();}
function answerSpell(w){if(quiz.locked)return;const input=$('#spellAnswer'),answer=input.value.trim().toLowerCase();if(!answer)return toast('先输入答案');quiz.locked=true;const ok=answer===w.word.toLowerCase();recordAnswer(ok,w);input.classList.add(ok?'correct':'wrong');input.disabled=true;$('#submitSpell').outerHTML=`<span style="align-self:center;color:${ok?'#3c7b59':'#c36150'}">${ok?'✓ 正确':'正确答案：'+w.word}</span>`;nextButton();}
function nextButton(){const host=$('#quizBody');host.insertAdjacentHTML('beforeend','<button class="primary quiz-next" id="nextQuiz">下一题 →</button>');$('#nextQuiz').onclick=()=>{quiz.index++;renderQuiz()};}

const reading={title:'Reading Comprehension · 示例练习',passage:'More and more adults are returning to education. Some want better job opportunities, while others simply enjoy learning new things. Online courses have made this easier because students can study at a convenient time and place. However, successful online learning still requires careful planning and self-discipline. Students who set clear weekly goals are more likely to complete their courses.',questions:[['Why do some adults return to education?',['Only to meet new people.','To improve work opportunities or enjoy learning.','Because online courses are compulsory.','To avoid making plans.'],1],['What has made adult learning easier?',['Shorter working hours.','Free textbooks.','Online courses.','Weekly examinations.'],2],['What does successful online learning require?',['Self-discipline.','Travel experience.','A large classroom.','A full-time teacher.'],0],['Who are more likely to finish a course?',['Students with clear weekly goals.','Students who never make plans.','Students who study only at night.','Students with many textbooks.'],0]]};
const cloze={title:'Cloze · 示例练习',passage:'Keeping healthy is not only about exercise. A balanced diet, enough sleep and a positive attitude are also important. Many people know this, ___ they still find it difficult to change old habits.',questions:[['请选择第 1 空的最佳答案',['and','but','so','or'],1],['“balanced diet” 最接近的含义是',['昂贵的食物','均衡饮食','快速用餐','严格节食'],1],['下列哪项也是健康生活的重要部分？',['熬夜','积极的态度','跳过早餐','停止运动'],1],['文中 “they” 指代谁？',['habits','people','attitudes','diets'],1],['本文主旨是',['健康需要多方面习惯','运动没有作用','改变习惯很容易','睡眠比饮食重要'],0]]};
function renderPractice(type='reading'){if(!$('#practicePanel'))return;const d=type==='reading'?reading:cloze;$('#practicePanel').innerHTML=`<span class="eyebrow">${d.title}</span><p class="passage">${d.passage}</p>${d.questions.map((q,qi)=>`<div class="exam-question"><b>${qi+1}. ${q[0]}</b><div class="exam-options">${q[1].map((o,oi)=>`<label><input type="radio" name="q${qi}" value="${oi}"> ${String.fromCharCode(65+oi)}. ${o}</label>`).join('')}</div></div>`).join('')}<button class="primary" id="submitPractice">提交答案</button><span id="practiceResult" style="margin-left:15px"></span>`;$('#submitPractice').onclick=()=>{let score=0;d.questions.forEach((q,i)=>{const a=$(`input[name="q${i}"]:checked`);if(a&&+a.value===q[2])score++});$('#practiceResult').textContent=`得分：${score} / ${d.questions.length}`;toast('练习已批改');};}
$$('.practice-type:not(.disabled)').forEach(b=>b.onclick=()=>{$$('.practice-type').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPractice(b.dataset.type)});renderPractice();

function renderBook(filter=''){const ids=[...new Set(state.wrong)],list=WORDS.filter(w=>ids.includes(w.id)&&(w.word.toLowerCase().includes(filter.toLowerCase())||w.meaning.includes(filter)));$('#bookCount').textContent=`${ids.length} 个错词`;$('#wordList').innerHTML=list.length?list.map(w=>`<article class="word-row"><div><h4>${w.word} <small>${w.phonetic}</small></h4><p>${w.meaning}</p></div><button data-speak="${w.word}">🔊</button></article>`).join(''):'<div class="empty">错词本还是空的。完成测试后，错题会自动出现在这里。</div>';$$('[data-speak]').forEach(b=>b.onclick=()=>speechSynthesis.speak(new SpeechSynthesisUtterance(b.dataset.speak)));}
$('#searchInput').oninput=e=>renderBook(e.target.value);$('#clearBook').onclick=()=>{if(confirm('确定清空全部错词记录吗？')){state.wrong=[];save();renderBook();updateStats()}};

const PAPERS=[
  ['2024年3月','2024年3月.pdf','2024年3月答案-详细解析.pdf'],['2022年9月','2022年9月.pdf','2022年9月答案-详细解析.pdf'],['2022年3月','2022年3月.pdf','2022年3月答案-详细解析.pdf'],['2021年3月','2021 年3月.pdf','2021年3月答案-详细解析.pdf'],['2019年9月','2019年9月.pdf','PETS3-真题答案2015-2019.pdf'],['2019年3月','2019年3月.pdf','PETS3-真题答案2015-2019.pdf'],['2018年9月','2018年9月.pdf','PETS3-真题答案2015-2019.pdf'],['2018年3月','2018年3月.pdf','PETS3-真题答案2015-2019.pdf'],['2017年9月','2017年9月.pdf','PETS3-真题答案2015-2019.pdf'],['2017年3月','2017年3月.pdf','PETS3-真题答案2015-2019.pdf'],['2016年9月','2016年9月.pdf','PETS3-真题答案2015-2019.pdf'],['2016年3月','2016年3月.pdf','PETS3-真题答案2015-2019.pdf'],['2015年9月','2015年9月.pdf','PETS3-真题答案2015-2019.pdf']
];
const AUDIO=[['2024年3月','2024年3月听力.mp3'],['2019年9月','2019年9月听力.mp3'],['2019年3月','2019年3月听力.mp3'],['2018年9月','2018年9月听力.mp3'],['2018年3月','2018年3月.mp3'],['2017年9月','2017年9月.mp3'],['2017年3月','2017年3月.mp3'],['2016年9月','2016年9月.mp3'],['2016年3月','2016年3月.mp3'],['2015年9月','2015年9月.mp3']];
const asset=(folder,file)=>`assets/${folder}/${encodeURIComponent(file)}`;
function renderPapers(){if(!$('#paperList'))return;$('#paperList').innerHTML=PAPERS.map((p,i)=>`<button class="paper-item${i===0?' active':''}" data-paper="${i}"><b>${p[0]}</b><small>全国英语等级考试三级 · PDF</small></button>`).join('');$$('[data-paper]').forEach(b=>b.onclick=()=>selectPaper(+b.dataset.paper));selectPaper(0)}
function selectPaper(i){const p=PAPERS[i];$$('.paper-item').forEach((b,j)=>b.classList.toggle('active',i===j));$('#paperTitle').textContent=`PETS3 ${p[0]}真题`;$('#paperMeta').textContent='原版试卷 · 可缩放与打印';$('#paperFrame').src=asset('papers',p[1]);$('#paperLink').href=asset('papers',p[1]);$('#answerLink').href=asset('answers',p[2]);}
function renderTracks(){if(!$('#trackList'))return;$('#trackList').innerHTML=AUDIO.map((a,i)=>`<button class="track-item" data-track="${i}"><b>♫ ${a[0]}听力</b><small>点击开始训练</small></button>`).join('');$$('[data-track]').forEach(b=>b.onclick=()=>selectTrack(+b.dataset.track));}
function selectTrack(i){const a=AUDIO[i];$$('.track-item').forEach((b,j)=>b.classList.toggle('active',i===j));$('#trackTitle').textContent=`${a[0]} PETS3 听力`;$('#trackHint').textContent='先不要查看答案，按考试要求完整播放一遍。';$('#audioPlayer').src=asset('audio',a[1]);$('#audioPlayer').play().catch(()=>{});const p=PAPERS.find(x=>x[0]===a[0]),link=$('#openListeningPaper');link.target='_self';if(p){link.href=asset('papers',p[1]);link.textContent=`打开 ${a[0]} 对应试卷`;link.style.pointerEvents='auto';link.style.opacity='1'}else{link.removeAttribute('href');link.textContent='暂未找到对应试卷';link.style.pointerEvents='none';link.style.opacity='.55'}}

const BASE_TIPS=[
 {id:'v1',cat:'词汇搭配',title:'动词 + 介词高频搭配',content:'depend on 依靠｜result in 导致｜contribute to 促成｜cope with 应对｜apply for 申请。注意介词后接名词或动名词。'},
 {id:'v2',cat:'词汇搭配',title:'易混词辨析',content:'affect 通常作动词“影响”；effect 通常作名词“影响、效果”。\naccept 接受；except 除……之外。'},
 {id:'g1',cat:'语法',title:'非谓语判断顺序',content:'先找句中谓语，再判断空格与主语的逻辑关系：主动常用 doing，被动常用 done，目的或将来倾向用 to do。'},
 {id:'g2',cat:'语法',title:'虚拟语气常见结构',content:'If I were... / I wish I had done... / It is essential that he (should) do...。看到 wish、suggest、essential 要提高警惕。'},
 {id:'r1',cat:'阅读',title:'转折后通常是重点',content:'but, however, yet, nevertheless, instead, in fact 后常出现作者真正观点，也是主旨题与推断题的高频定位处。'},
 {id:'r2',cat:'阅读',title:'阅读题定位三步法',content:'先读题干划关键词；回原文找同义替换；最后排除绝对化、偷换概念和无中生有的选项。'},
 {id:'l1',cat:'听力',title:'预读选项，预测场景',content:'播放前快速圈出人物、地点、数字和差异词。选项都是时间时，重点听更正与最终决定，而非第一个数字。'},
 {id:'l2',cat:'听力',title:'常见信号词',content:'actually 表示修正；but/however 表示转折；so 表示结论；first/then/finally 表示顺序；the point is 引出核心。'},
 {id:'w1',cat:'写作',title:'议论文三段式骨架',content:'第一段明确话题与立场；第二段给出 2 个理由并配例子；第三段总结并提出建议。连接词要准确，避免堆砌。'},
 {id:'w2',cat:'写作',title:'实用衔接表达',content:'To begin with... / In addition... / A good example is... / Therefore... / From my perspective...。每段围绕一个中心展开。'},
 {id:'s1',cat:'考试策略',title:'阅读时间分配',content:'先做定位清晰的细节题，再做主旨和推断题。单题卡住超过 2 分钟先标记，完成整篇后再返回。'},
 {id:'s2',cat:'考试策略',title:'错题复盘四问',content:'考了什么？我为什么错？正确依据在哪里？下次看到什么信号能避开？只抄答案不等于复盘。'}
];
let tipCat='全部';
function allTips(){return [...BASE_TIPS,...state.customTips]}
function renderTips(){if(!$('#tipGrid'))return;const cats=['全部','词汇搭配','语法','阅读','听力','写作','考试策略'];$('#tipCats').innerHTML=cats.map(c=>`<button class="${c===tipCat?'active':''}" data-tipcat="${c}">${c}</button>`).join('');const q=$('#tipSearch').value.trim().toLowerCase();const list=allTips().filter(t=>(tipCat==='全部'||t.cat===tipCat)&&(!q||(t.title+t.content).toLowerCase().includes(q)));$('#tipGrid').innerHTML=list.length?list.map(t=>`<article class="tip-card ${state.tipsCompleted.includes(t.id)?'done':''}"><span class="tag">${t.cat}</span><h3>${t.title}</h3><p>${t.content}</p><div class="tip-actions"><button data-tipdone="${t.id}">${state.tipsCompleted.includes(t.id)?'↩ 取消掌握':'✓ 标记掌握'}</button>${String(t.id).startsWith('custom-')?`<button data-tipdelete="${t.id}">删除</button>`:''}</div></article>`).join(''):'<div class="empty">没有找到相关知识点。</div>';$$('[data-tipcat]').forEach(b=>b.onclick=()=>{tipCat=b.dataset.tipcat;renderTips()});$$('[data-tipdone]').forEach(b=>b.onclick=()=>{const id=b.dataset.tipdone;state.tipsCompleted=state.tipsCompleted.includes(id)?state.tipsCompleted.filter(x=>x!==id):[...state.tipsCompleted,id];save();renderTips()});$$('[data-tipdelete]').forEach(b=>b.onclick=()=>{state.customTips=state.customTips.filter(x=>x.id!==b.dataset.tipdelete);save();renderTips()});}
$('#tipSearch').oninput=renderTips;$('#addTip').onclick=()=>$('#tipDialog').showModal();$('#saveTip').onclick=e=>{const title=$('#newTipTitle').value.trim(),content=$('#newTipContent').value.trim();if(!title||!content){e.preventDefault();return toast('请填写标题和内容')}state.customTips.push({id:`custom-${Date.now()}`,cat:$('#newTipCat').value,title,content});save();$('#newTipTitle').value='';$('#newTipContent').value='';renderTips();toast('知识点已保存')};
renderPapers();renderTracks();renderTips();initDay();updateStats();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
